name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Signing Apk
        run: |
          dd if=.github/workflows/android.jks.des3|openssl des3 -pbkdf2 -d -k ${{ secrets.ANDROID_JKS_PASSWORD }}|tar zxvf -
          echo 'storeFile=../android.jks' >> local.properties
          echo 'storePassword=${{ secrets.STORE_PASSWORD }}' >> local.properties
          echo 'keyAlias=${{ secrets.KEY_ALIAS }}' >> local.properties
          echo 'keyPassword=${{ secrets.KEY_PASSWORD }}' >> local.properties
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: moebooru.apk
        uses: actions/upload-artifact@v2
        with:
          name: moebooru.apk
          path: $GITHUB_WORKSPACE/app/build/outputs/apk/*/release/*